#!/bin/bash

SIM_DIR="./vcs_dig"
mkdir -p $SIM_DIR

vcs -sverilog \
    -ntb_opts uvm \
    -timescale=1ns/1ps \
    -debug_access+all \
    -f /work/dku/RNM_testbench/scripts/vcs_run.f \
    -pvalue+tb_top.ENABLE_AMS=0 \
    -pvalue+tb_top.TEST_DUT=0 \
    -Mdir=$SIM_DIR/csrc \
    -o $SIM_DIR/simv \
    -l $SIM_DIR/vcs_compile.log \
    "$@"

# Step 2: Check if compilation succeeded
if [ $? -eq 0 ]; then
    echo "Compilation Successful. Starting Simulation..."
    
    # Run the executable generated by VCS
    $SIM_DIR/simv +UVM_TESTNAME=comp_base_test -l $SIM_DIR/vcs_sim.log
else
    echo "VCS Compilation Failed. Check $SIM_DIR/vcs_compile.log"
    exit 1
fi